# 头部导航
menu:
  -
    name: "首页"
    path: "/"
  -
    name: "归档"
    path: "/archives/"
  -
    name: "标签"
    path: "/tags/"
  -
    name: "分类"
    path: "/categories/"
  -
    name: "友链"
    path: "/friends/"
  -
    name: "关于"
    path: "/about/"

nav_name: ZUO″のBlog

motto: '总结技术与生活'

Github: https://github.com/zuomm/ # github快速通道

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss: 

# 自定义样式文件位置
custom_style:

# 代码高亮主题
highlight_theme: "night eighties"

# 目录渲染
toc: true

# 开启数学公式渲染
mathjax: true

# 建站时间. 格式：YYYY-MM-DD
start_time: "2019-02-20"

# PV统计
# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: JWBYFc6i9NYC0PWxMxlcLO7Y-gzGzoHsz # 填写您的appid
  appkey: Hc7vwb5cPwK1CaPaeXQfdHAx # 填写您的appkey
  comment: true # 是否开启评论系统
  count: true # 是否开启文章统计

# 访问提醒功能
# 需要保证leancloud.comment为true
welcome: 
  enable: true
  interval: 30hexo

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
passwords: 
  - efe07af7441da2b69c4a41e42e73be4db47f66010a56900788a458354a7373ec # godbmw

# 页脚
footer:
  -
    title: "博客推荐"
    children:
      -
        name: "GodBMW"
        path: "https://godbmw.com/"
      - 
        name: "阮一峰的个人网站"
        path: "http://ruanyifeng.com/"
  -
    title: "系列教程"
    children:
      -
        name: "webpack4系列教程"
        path: "https://godbmw.com/categories/webpack4%E7%B3%BB%E5%88%97%E6%95%99%E7%A8%8B/"
      -
        name: "设计模式手册"
        path: "https://godbmw.com/design-patterns/"
  -
    title: "找到我"
    children:
      -
        name: "知乎"
        path: "https://www.zhihu.com/people/zuomiaomiao/activities"
      -
        name: "博客园"
        path: "https://www.cnblogs.com/mmzuo-798/"
      -
        name: "CSDN"
        path: "https://blog.csdn.net/journey0804"

footer_contact: "Email: 1542934395@qq.com"

# 文章底部版权
copyright: 
  enable: true # 是否开启版权保护
  author: zuomiaomiao # 您的名字
  license: '本博客所有文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 许可协议。转载请注明出处！'

# 打赏
reward:
  -
    src: /images/wechat.png # 二维码图片地址
    alt: "WeChat" # 二维码信息
  -
    src: /images/alipay.png # 支付宝图片地址
    alt: "AliPay"

# 友链
friends:
  -
    nickname: ZuoMiaomiao # 友链名称
    avatar: /images/friends/godbmw.jpeg # 友链头像
    site: https://godbmw.com/ # 友链地址
    meta: 主题作者 # 友链介绍
    show: true # 是否展示此友链

# 如果您的友链头像都保存在其他服务器上，可以通过更改friends_avatar_cdn字段来配置前缀地址
# 注意：此功能需要正确开启「友链」页面 
friends_avatar_cdn: "https://godbmw.com/blog-static"

# 开启侧边栏分享链接
share:
  twitter: true # true 是开启
  facebook: false # false 是关闭
  weibo: true
  qq: true
  wechat: true

# SEO优化
# 注意：360和谷歌的自动推送，需要对应平台的跟踪代码的id，请查阅对应平台的手册内容。
analytics:
  baidu:
    enable: true # 开启对百度的自动链接
  google:
    enable: true # 开启对Google的自动推送
    id: # Google跟踪代码的id
  "360":
    enable: true # 开启对360的自动推送
    id: # 360跟踪代码的id

 